### ISSUE TITLE
E2.1 - Instructions for Scharr Kernel

### ISSUE THREAD

**Issue by mattdouthwaite** [HPCE/hpce-2015-cw1#1]
In E2.1 the instruction says: 
"The function should calclate the vertical and horizontal strength G_x and G_y,..."

I'm not sure what you mean by the "vertical and horizontal strength"? Could you clarify?

I've tried the operations shown in the wiki page you link to; convolving the matrices given there with the original sample using conv2, but I don't get the expected results.
Thanks.

**Comment by mazei513** [comment]
https://en.wikipedia.org/wiki/Kernel_(image_processing)

Refer to the blur kernel. You should be performing the same operation. The wiki page linked has the explanation of how to use kernels.

**Comment by m8pple** [comment]
I pointed to the defs of G_x and G_y in the wikipedia page.

As @mazei513 notes, the process of turning it into a kernel should be similar to that
of blur.

Is this issue that the result using conv2 gives completely wrong results (no edges), or that
the edges are the wrong brightness?

**Comment by Ah4412** [comment]
Hey, 
I implemented the Scharr edge detection kernel algorithm, following:
"G = sqrt(G_x^2+G_y^2);
 pixel = min(G/8, 1);"

but when running "effects.scharr_scalar([0.5 0.6 0.7; 0.5 0.6 0.7; 0.5 0.6 0.7]); % == 0.4"
I get G= 0.8 as a result hence pixel = 0.1.
Shouldn't the combination to the output pixel be "pixel = min(G/2, 1);" ? 
(that way the brightness for the cameraman seems to match )

**Comment by mattdouthwaite** [comment]
Thanks for the comments. I'd used the instructions on the wikipedia page. My problem is that I am not getting the same as the examples given in the coursework instructions in E2.1:

% Some basic tests
effects.scharr_scalar(zeros(3)); % == 0
effects.scharr_scalar([1 1 1 ; 0.5 0.5 0.5 ; 0 0 0]); % == 1
effects.scharr_scalar([0.5 0.6 0.7; 0.5 0.6 0.7; 0.5 0.6 0.7]); % == 0.4

All zeros is fine. If I put the second example in I get 0.5 (not 1) and the third I get 0.1 (not 0.4), in the same manner as the previous comment.

Assuming the example results are correct, I'm wondering if I'm either doing something wrong in the convolution or producing the output scalar incorrectly? The function I am using is 'conv2' and I have applied the 'same' parameter to get an output 3x3 matrix. I then combine using:

"G = sqrt(G_x^2+G_y^2);
pixel = min(G/8, 1);"

Pixel is now a 3x3 matrix though, so I select the central element, (2,2). Is this correct or should I have obtained a scalar in the previous step?

I can post code if that if that would help (I can't remember if that was ok for these earlier coursework or not).

**Comment by cianyleow** [comment]
@mattdouthwaite & @Ah4412 make sure that you're using the Scharr matrix and not the Sobel one (https://en.wikipedia.org/wiki/Sobel_operator#Alternative_operators)

**Comment by mattdouthwaite** [comment]
@cianyleow Ah, ok. That solved it, thanks!

**Comment by mattdouthwaite** [comment]
Before closing the issue, I'd say that the original confusion was caused by the term 'strength'. Although we are just expected to perform the operation in the wiki article, I think this is a little confusing still.

Perhaps a better way would be to say: "the vertical and horizontal 'gradient', 'change' or 'derivatives' "? (If I have understood correctly that is what the matrices G_x and G_y are?)
